"""Bundled, curated lists of well-known package names used by the typosquat
heuristic (see ``typosquat.py``).

This is a starter list, not a live download-ranked feed — there is no
network call backing it. Expand it (or swap in a generated top-N-by-downloads
list) as needed; false negatives are expected for anything not on this list.
"""

from __future__ import annotations

POPULAR_NPM_PACKAGES: frozenset[str] = frozenset({
    "react", "react-dom", "react-router", "react-router-dom", "redux", "react-redux",
    "vue", "vuex", "vue-router", "svelte", "sveltekit",
    "angular", "@angular/core", "@angular/common",
    "lodash", "underscore", "ramda", "ramda-adjunct",
    "jquery", "express", "koa", "fastify", "hapi", "restify",
    "axios", "node-fetch", "request", "superagent", "got", "isomorphic-fetch",
    "webpack", "webpack-cli", "webpack-dev-server", "html-webpack-plugin",
    "mini-css-extract-plugin", "babel-core", "@babel/core", "@babel/preset-env",
    "@babel/cli", "rollup", "vite", "esbuild", "parcel", "snowpack",
    "eslint", "prettier", "stylelint", "jshint", "jslint",
    "jest", "mocha", "chai", "jasmine", "karma", "cypress", "playwright",
    "puppeteer", "sinon", "ava", "tap", "vitest", "testcafe",
    "typescript", "ts-node", "tslib", "flow-bin", "tsx", "swc", "@swc/core",
    "chalk", "commander", "yargs", "minimist", "inquirer", "ora", "figlet", "boxen",
    "cli-progress", "cli-table3",
    "debug", "winston", "pino", "bunyan", "morgan", "loglevel",
    "moment", "dayjs", "date-fns", "luxon",
    "uuid", "nanoid", "shortid", "cuid",
    "dotenv", "cross-env", "config", "rc", "convict",
    "lodash.debounce", "lodash.merge", "lodash.throttle",
    "classnames", "clsx", "prop-types",
    "next", "nuxt", "gatsby", "remix", "astro", "solid-js",
    "tailwindcss", "bootstrap", "bulma", "sass", "less", "postcss", "autoprefixer",
    "socket.io", "ws", "mqtt", "engine.io",
    "mongoose", "sequelize", "knex", "typeorm", "prisma",
    "pg", "mysql2", "sqlite3", "redis", "ioredis",
    "graphql", "apollo-server", "apollo-client", "@apollo/client",
    "jsonwebtoken", "bcrypt", "bcryptjs", "passport", "helmet", "cors",
    "body-parser", "multer", "cookie-parser", "express-session",
    "lint-staged", "husky", "nodemon", "concurrently", "rimraf", "shelljs",
    "semver", "glob", "minimatch", "fs-extra", "chokidar", "globby",
    "async", "bluebird", "rxjs", "p-limit", "p-queue",
    "immutable", "immer",
    "styled-components", "emotion", "@emotion/react", "@emotion/styled",
    "core-js", "regenerator-runtime", "whatwg-fetch", "abort-controller",
    "zod", "yup", "joi", "ajv", "class-validator",
    "pm2", "forever", "serve", "http-server", "live-server",
    "electron", "electron-builder", "electron-updater",
    "react-native", "expo",
    "d3", "three", "chart.js", "recharts", "victory", "plotly.js",
    "lerna", "nx", "turbo", "changesets",
    "npm", "yarn", "pnpm", "npx",
    "react-dom-router", "react-scripts", "create-react-app",
    "eslint-config-airbnb", "eslint-plugin-react", "eslint-plugin-import",
    "husky-init", "commitlint", "@commitlint/cli",
    "sharp", "node-sass", "canvas", "sqlite", "better-sqlite3",
    "aws-sdk", "@aws-sdk/client-s3", "firebase", "firebase-admin",
    "stripe", "twilio", "sendgrid",
    "vue-cli", "@vue/cli", "quasar",
})

POPULAR_PYPI_PACKAGES: frozenset[str] = frozenset({
    "requests", "urllib3", "certifi", "idna", "charset-normalizer", "chardet",
    "numpy", "pandas", "scipy", "matplotlib", "seaborn", "scikit-learn", "statsmodels",
    "django", "flask", "fastapi", "starlette", "uvicorn", "gunicorn", "tornado",
    "aiohttp", "sanic", "bottle", "pyramid",
    "sqlalchemy", "alembic", "psycopg2", "psycopg2-binary", "pymysql", "pymongo", "redis",
    "click", "typer", "docopt",
    "pyyaml", "toml", "jsonschema", "tomli",
    "pytest", "pytest-cov", "pytest-mock", "tox", "nose",
    "setuptools", "wheel", "pip", "packaging", "build", "twine",
    "boto3", "botocore", "awscli", "google-cloud-storage", "azure-storage-blob",
    "cryptography", "pyjwt", "bcrypt", "passlib", "paramiko", "pynacl",
    "pillow", "opencv-python", "imageio",
    "beautifulsoup4", "lxml", "html5lib", "scrapy", "soupsieve",
    "celery", "kombu", "billiard",
    "jinja2", "markupsafe", "itsdangerous", "werkzeug",
    "attrs", "cattrs", "pydantic", "marshmallow", "dataclasses-json",
    "six", "python-dateutil", "pytz", "tzdata", "arrow", "pendulum",
    "tqdm", "rich", "colorama", "termcolor",
    "uwsgi",
    "transformers", "torch", "tensorflow", "keras", "huggingface-hub",
    "datasets", "accelerate", "sentencepiece",
    "openai", "anthropic", "langchain", "langchain-core",
    "selenium", "playwright",
    "flask-sqlalchemy", "flask-migrate", "flask-login",
    "djangorestframework", "django-cors-headers",
    "gevent", "greenlet", "eventlet",
    "cffi", "pycparser",
    "protobuf", "grpcio",
    "pyarrow", "fastparquet",
    "networkx", "sympy",
    "nltk", "spacy", "gensim",
    "faker", "factory-boy",
    "black", "isort", "flake8", "pylint", "mypy", "ruff", "bandit", "pre-commit",
    "virtualenv", "pipenv", "poetry", "uv",
    "cachetools", "more-itertools", "toolz",
    "xmltodict", "defusedxml",
    "psutil", "watchdog",
    "docker", "kubernetes",
    "elasticsearch", "pymssql",
    "flask-cors", "flask-restful",
    "pytest-asyncio", "pytest-xdist",
    "coverage", "hypothesis",
})
